from typing import Dict

TEXTS: Dict[str, Dict[str, str]] = {
    "ru": {
        # Подписчики
        "sub_menu_header": "📢 <b>Предложка канала {channel_title}</b>\n{rating_str}\nВыберите действие ниже:",
        "rating_line": "⭐ <b>Рейтинг:</b> {avg_rating} / 5.0 ({count} оценок)\n",
        "btn_idea": "💡 Предложить идею",
        "btn_question_all": "❓ Задать вопрос владельцам",
        "btn_question_admin": "👤 Вопрос конкретному админу",
        "btn_review": "⭐ Оставить отзыв и оценку",
        "choose_anonymity": "Как вы хотите отправить сообщение?",
        "btn_anon": "🕵️ Анонимно",
        "btn_public": "👤 Открыто (@{username})",
        "prompt_send_idea": "💡 Напишите вашу идею или отправьте медиафайл (фото/видео/голосовое):",
        "prompt_send_question": "❓ Напишите ваш вопрос (можно прикрепить медиафайл):",
        "prompt_select_rating": "⭐ Выберите вашу оценку каналу от 1 до 5 звезд:",
        "prompt_send_review_text": "✍️ Напишите краткий комментарий к вашей оценке (или нажмите «Пропустить»):",
        "btn_skip": "⏩ Пропустить",
        "msg_sent_success": "✅ Ваше сообщение успешно отправлено администраторам!",
        "review_saved_success": "🎉 Спасибо за ваш отзыв! Оценка сохранена.",
        "review_cooldown_error": "⏳ Вы уже оставляли отзыв. Изменить его можно будет через {days_left} дн.",
        "user_banned_error": "🛑 Администрация канала ограничила вам доступ к отправке сообщений.",
        "err_channel_not_found_subscriber": "❌ Канал не найден или ссылка устарела.",
        "prompt_choose_admin": "Выберите администратора, которому хотите задать вопрос:",
        "media_placeholder": "[Медиафайл]",

        # Кнопки для админа в карточке сообщения
        "btn_reply_private": "💬 Ответить лично",
        "btn_reply_public": "📢 Публичный ответ в канал",
        "btn_publish_idea": "🚀 Опубликовать в канал",
        "btn_ban_user": "🚫 Заблокировать",
        "btn_unban_user": "🔄 Разблокировать",
        "btn_back": "🔙 Назад",

        # Уведомления админу в ЛС
        "admin_new_idea": "📥 <b>Новое сообщение для канала [{channel_title}]</b>\n📌 <b>Тип:</b> 💡 Идея\n👤 <b>Автор:</b> {sender_info}\n\n💬 {text}",
        "admin_new_question": "📥 <b>Новое сообщение для канала [{channel_title}]</b>\n📌 <b>Тип:</b> ❓ Вопрос\n👤 <b>Автор:</b> {sender_info}\n\n💬 {text}",
        "admin_reply_priv_prompt": "💬 Введите текст личного ответа для подписчика:",
        "admin_reply_pub_prompt": "📢 Введите текст ответа, который будет опубликован в канале:",
        "sub_received_priv_reply": "💬 <b>Ответ от администрации канала [{channel_title}]:</b>\n\n{text}",
        "sub_published_in_channel": "🎉 Ваш вопрос и ответ на него были опубликованы в канале!",
        "sub_idea_published": "🎉 Ваша идея была опубликована в канале!",
        "reply_sent_to_user_success": "✅ Ваш ответ успешно доставлен подписчику!",
        "post_published_success": "✅ Пост успешно опубликован в канале!",
        "card_banned_text": "🛑 Пользователь заблокирован в этом канале.",
        "err_msg_not_found": "❌ Сообщение не найдено.",
        "err_cant_reply": "❌ Не удалось отправить ответ. Возможно, подписчик заблокировал бота.",
        "err_publish_failed": "❌ Ошибка при публикации в канал: {error}",
        "admin_card_processed": "📥 <b>Вопрос обработан</b>\n❓ <b>Вопрос:</b> <i>«{orig_text}»</i>\n\n✅ <b>Админ {actor_name} ({action_str}):</b>\n<i>«{answer_text}»</i>",
        "action_priv_reply": "ответил лично",
        "action_pub_reply": "ответил в канал",
        "action_published_idea": "опубликовал идею в канал",

        # Шаблоны публикаций в канале
        "anon_question_title": "❓ <b>Анонимный вопрос</b>",
        "public_question_title_open": "❓ <b>Вопрос от {author_str}</b>",
        "channel_reply_header": "💬 <b>Ответ:</b>",
        "channel_ask_prompt": "🤖 <i>Задать свой вопрос: {bot_link}</i>",
        "idea_post_header_anon": "💡 <b>Пост от анонимного подписчика</b>",
        "idea_post_header_public": "💡 <b>Пост от {author_str}</b>",
        "idea_suggest_prompt": "🤖 <i>Предложить свою идею: {bot_link}</i>",

        # Регистрация канала
        "channel_setup_success": "🎉 <b>Канал «{channel_title}» успешно подключен!</b>\n\n🔗 Ваша уникальная ссылка предложки для подписчиков:\n<code>{sub_link}</code>\n\nРазместите эту ссылку в описании канала или в постах!",
        "channel_setup_temp_post": "⚙️ <b>Настройка Onward:</b> Администратору нужно нажать кнопку ниже для завершения подключения:",
        "btn_complete_setup": "🔗 Завершить настройку Onward",
        "bot_removed_from_channel": "⚠️ Бот Onward был удален из канала. Прием сообщений временно приостановлен.",
        "err_not_channel_admin": "❌ Ошибка: Вы не являетесь администратором этого канала.",
        "err_check_rights_failed": "❌ Не удалось проверить права. Убедитесь, что бот добавлен в канал.",
        "reg_success": "🎉 <b>Регистрация завершена!</b>\n\n🔗 Ссылка предложки для вашего канала:\n<code>{sub_link}</code>",
        "err_inv_not_admin": "❌ Ошибка: Чтобы стать админом бота, вы должны сначала стать админом канала в Telegram.",
        "err_channel_not_found": "❌ Канал не найден или бот из него удален.",
        "coadmin_registered_success": "✅ Вы успешно зарегистрированы как администратор этого канала в Onward!",
        "coadmin_already_registered": "ℹ️ Вы уже являетесь администратором этого канала в боте.",

        # Админ Панель
        "admin_welcome_no_channels": "👋 <b>Добро пожаловать в Onward!</b>\n\nЧтобы начать, добавьте меня в свой Telegram-канал как администратора. Я автоматически сгенерирую ссылку предложки для ваших подписчиков!",
        "admin_panel_welcome": "⚙️ <b>Панель управления Onward</b>\nВыберите канал для настройки:",
        "admin_channel_manage": "📢 <b>Управление каналом «{ch_title}»</b>\nСтатус: {status}\n\n🔗 <b>Ссылка предложки:</b>\n<code>{sub_link}</code>",
        "status_premium": "⭐ Premium",
        "status_free": "🆓 Free",
        "btn_set_btns": "⚙️ Настройки кнопок",
        "btn_set_profile": "👤 Мой профиль админа",
        "btn_add_coadmin": "👥 Добавить со-админа",
        "btn_ban_list": "🚫 Заблокированные юзеры",
        "btn_premium": "⭐ Onward Premium",
        "btn_manage_premium": "⭐ Настройки Onward Premium",
        "premium_settings_header": "⭐ <b>Настройки Onward Premium:</b>",
        "btn_set_welcome": "🎨 Кастомное приветствие",
        "btn_set_autoreply": "🤖 Кастомный автоответ",
        "btn_copyright_on": "✅ Подпись бота под постами",
        "btn_copyright_off": "❌ Подпись бота скрыта",
        "prompt_enter_welcome": "🎨 Введите новый текст приветствия, который увидят подписчики при входе в предложку:",
        "welcome_saved_success": "✅ Кастомное приветствие сохранено!",
        "welcome_reset_success": "🔄 Приветствие сброшено к стандартному.",
        "prompt_enter_autoreply": "🤖 Введите текст автоответа, который получит подписчик сразу после отправки сообщения:",
        "autoreply_saved_success": "✅ Автоответ успешно сохранен!",
        "autoreply_reset_success": "🔄 Автоответ отключен.",
        "btn_reset": "🔄 Сбросить",
        "btn_back_channels": "🔙 Назад к списку",
        "header_set_btns": "⚙️ <b>Настройки отображения кнопок для подписчиков:</b>",
        "header_set_profile": "👤 <b>Настройки отображения вашего профиля в предложке:</b>",
        "btn_accepts_on": "✅ Принимать личные вопросы",
        "btn_accepts_off": "❌ Не принимать личные вопросы",
        "disp_anon_title": "Админ №X",
        "disp_name_title": "Имя",
        "disp_username_title": "@username",
        "btn_unban_id": "🔓 Разблокировать (ID: {user_id})",
        "coadmin_text": "👥 <b>Ссылка для добавления со-админа:</b>\n<code>{inv_link}</code>\n\nПерешлите эту ссылку второму администратору. Он должен быть администратором вашего канала в Telegram.",
        "ban_list_empty": "🎉 В этом канале нет заблокированных пользователей.",
        "ban_list_header": "🚫 <b>Заблокированные пользователи канала:</b>",
        "toast_unbanned": "✅ Пользователь успешно разблокирован!",

        # Оплата Stars
        "premium_menu_text": "⭐ <b>Onward Premium</b>\n\nПодключите Premium и откройте продвинутые возможности для канала:\n• 🎨 Кастомное приветствие и правила\n• 🤖 Настройка автоответа подписчикам\n• 🚫 Отключение копирайта бота\n• 📊 Подробная статистика и экспорт\n\nВыберите тариф для оплаты Звёздами Telegram:",
        "btn_plan_1d": "⭐ 1 День — 5 XTR",
        "btn_plan_7d": "⭐ 7 Дней — 20 XTR",
        "btn_plan_1m": "⭐ 1 Месяц — 50 XTR",
        "btn_plan_3m": "⭐ 3 Месяца — 120 XTR",
        "btn_plan_life": "⭐ Навсегда — 350 XTR",
        "plan_1d_title": "Onward Premium (1 день)",
        "plan_7d_title": "Onward Premium (7 дней)",
        "plan_1m_title": "Onward Premium (1 месяц)",
        "plan_3m_title": "Onward Premium (3 месяца)",
        "plan_life_title": "Onward Premium (Навсегда)",
        "invoice_desc": "Премиум доступ для канала {channel_id}",
        "pay_success": "🎉 <b>Оплата прошла успешно!</b>\n\nДля канала <code>{channel_id}</code> успешно активирован статус <b>Onward Premium</b>.\nСпасибо за поддержку проекта!"
    },

    "en": {
        "sub_menu_header": "📢 <b>Suggestion box for {channel_title}</b>\n{rating_str}\nChoose an action below:",
        "rating_line": "⭐ <b>Rating:</b> {avg_rating} / 5.0 ({count} reviews)\n",
        "btn_idea": "💡 Suggest an idea",
        "btn_question_all": "❓ Ask channel owners",
        "btn_question_admin": "👤 Ask specific admin",
        "btn_review": "⭐ Leave review & rating",
        "choose_anonymity": "How would you like to send this message?",
        "btn_anon": "🕵️ Anonymously",
        "btn_public": "👤 Publicly (@{username})",
        "prompt_send_idea": "💡 Type your idea or send media (photo/video/voice):",
        "prompt_send_question": "❓ Type your question (media attachments supported):",
        "prompt_select_rating": "⭐ Rate the channel from 1 to 5 stars:",
        "prompt_send_review_text": "✍️ Write a short comment (or tap Skip):",
        "btn_skip": "⏩ Skip",
        "msg_sent_success": "✅ Your message has been sent to the admins!",
        "review_saved_success": "🎉 Thank you for your review!",
        "review_cooldown_error": "⏳ You have already left a review. You can update it in {days_left} days.",
        "user_banned_error": "🛑 The channel administration has restricted you from sending messages.",
        "err_channel_not_found_subscriber": "❌ Channel not found or link expired.",
        "prompt_choose_admin": "Choose an admin to ask your question:",
        "media_placeholder": "[Media File]",

        "btn_reply_private": "💬 Reply privately",
        "btn_reply_public": "📢 Post reply to channel",
        "btn_publish_idea": "🚀 Publish to channel",
        "btn_ban_user": "🚫 Ban user",
        "btn_unban_user": "🔄 Unban user",
        "btn_back": "🔙 Back",

        "admin_new_idea": "📥 <b>New message for [{channel_title}]</b>\n📌 <b>Type:</b> 💡 Idea\n👤 <b>Author:</b> {sender_info}\n\n💬 {text}",
        "admin_new_question": "📥 <b>New message for [{channel_title}]</b>\n📌 <b>Type:</b> ❓ Question\n👤 <b>Author:</b> {sender_info}\n\n💬 {text}",
        "admin_reply_priv_prompt": "💬 Enter text for private reply to subscriber:",
        "admin_reply_pub_prompt": "📢 Enter text for public reply to be posted in channel:",
        "sub_received_priv_reply": "💬 <b>Reply from [{channel_title}] administration:</b>\n\n{text}",
        "sub_published_in_channel": "🎉 Your question and answer have been published in the channel!",
        "sub_idea_published": "🎉 Your idea has been published in the channel!",
        "reply_sent_to_user_success": "✅ Your reply was successfully delivered to subscriber!",
        "post_published_success": "✅ Post successfully published in channel!",
        "card_banned_text": "🛑 User banned in this channel.",
        "err_msg_not_found": "❌ Message not found.",
        "err_cant_reply": "❌ Could not send reply. The subscriber may have blocked the bot.",
        "err_publish_failed": "❌ Publishing error: {error}",
        "admin_card_processed": "📥 <b>Message processed</b>\n❓ <b>Question:</b> <i>«{orig_text}»</i>\n\n✅ <b>Admin {actor_name} ({action_str}):</b>\n<i>«{answer_text}»</i>",
        "action_priv_reply": "replied privately",
        "action_pub_reply": "posted reply to channel",
        "action_published_idea": "published idea to channel",

        "anon_question_title": "❓ <b>Anonymous Question</b>",
        "public_question_title_open": "❓ <b>Question from {author_str}</b>",
        "channel_reply_header": "💬 <b>Answer:</b>",
        "channel_ask_prompt": "🤖 <i>Ask a question or suggest an idea: {bot_link}</i>",
        "idea_post_header_anon": "💡 <b>Subscriber Idea</b>",
        "idea_post_header_public": "💡 <b>Idea from {author_str}</b>",
        "idea_suggest_prompt": "🤖 <i>Suggest an idea: {bot_link}</i>",

        "channel_setup_success": "🎉 <b>Channel «{channel_title}» successfully connected!</b>\n\n🔗 Your unique suggestion link for subscribers:\n<code>{sub_link}</code>\n\nPlace this link in your channel description or posts!",
        "channel_setup_temp_post": "⚙️ <b>Onward Setup:</b> The administrator needs to press the button below to complete setup:",
        "btn_complete_setup": "🔗 Complete Onward Setup",
        "bot_removed_from_channel": "⚠️ The Onward bot was removed from the channel. Receiving messages paused.",
        "err_not_channel_admin": "❌ Error: You are not an administrator of this channel.",
        "err_check_rights_failed": "❌ Could not verify permissions. Ensure the bot is added to the channel.",
        "reg_success": "🎉 <b>Registration complete!</b>\n\n🔗 Suggestion link for your channel:\n<code>{sub_link}</code>",
        "err_inv_not_admin": "❌ Error: To become a bot admin, you must first be an admin of the channel in Telegram.",
        "err_channel_not_found": "❌ Channel not found or bot was removed.",
        "coadmin_registered_success": "✅ You have been successfully registered as a channel admin in Onward!",
        "coadmin_already_registered": "ℹ️ You are already registered as an admin for this channel.",

        "admin_welcome_no_channels": "👋 <b>Welcome to Onward!</b>\n\nTo start, add me as an administrator to your Telegram channel. I will automatically generate a suggestion box link for your subscribers!",
        "admin_panel_welcome": "⚙️ <b>Onward Control Panel</b>\nSelect a channel to configure:",
        "admin_channel_manage": "📢 <b>Channel Management «{ch_title}»</b>\nStatus: {status}\n\n🔗 <b>Suggestion link:</b>\n<code>{sub_link}</code>",
        "status_premium": "⭐ Premium",
        "status_free": "🆓 Free",
        "btn_set_btns": "⚙️ Button settings",
        "btn_set_profile": "👤 My admin profile",
        "btn_add_coadmin": "👥 Add co-admin",
        "btn_ban_list": "🚫 Banned users",
        "btn_premium": "⭐ Onward Premium",
        "btn_manage_premium": "⭐ Onward Premium Settings",
        "premium_settings_header": "⭐ <b>Onward Premium Settings:</b>",
        "btn_set_welcome": "🎨 Custom Welcome Message",
        "btn_set_autoreply": "🤖 Custom Auto-reply",
        "btn_copyright_on": "✅ Bot copyright enabled",
        "btn_copyright_off": "❌ Bot copyright hidden",
        "prompt_enter_welcome": "🎨 Enter a new welcome message for subscribers:",
        "welcome_saved_success": "✅ Custom welcome message saved!",
        "welcome_reset_success": "🔄 Welcome message reset to default.",
        "prompt_enter_autoreply": "🤖 Enter an auto-reply message sent to subscribers after submission:",
        "autoreply_saved_success": "✅ Auto-reply saved!",
        "autoreply_reset_success": "🔄 Auto-reply disabled.",
        "btn_reset": "🔄 Reset",
        "btn_back_channels": "🔙 Back to list",
        "header_set_btns": "⚙️ <b>Button display settings for subscribers:</b>",
        "header_set_profile": "👤 <b>Your profile display settings:</b>",
        "btn_accepts_on": "✅ Accept direct questions",
        "btn_accepts_off": "❌ Do not accept direct questions",
        "disp_anon_title": "Admin #X",
        "disp_name_title": "Name",
        "disp_username_title": "@username",
        "btn_unban_id": "🔓 Unban (ID: {user_id})",
        "coadmin_text": "👥 <b>Link to add a co-admin:</b>\n<code>{inv_link}</code>\n\nForward this link to another administrator. They must be an admin of your Telegram channel.",
        "ban_list_empty": "🎉 There are no banned users in this channel.",
        "ban_list_header": "🚫 <b>Banned users for this channel:</b>",
        "toast_unbanned": "✅ User successfully unbanned!",

        "premium_menu_text": "⭐ <b>Onward Premium</b>\n\nUnlock advanced features for your channel:\n• 🎨 Custom welcome & rules\n• 🤖 Custom auto-replies\n• 🚫 Remove bot branding\n• 📊 Detailed analytics & export\n\nChoose a plan using Telegram Stars:",
        "btn_plan_1d": "⭐ 1 Day — 5 XTR",
        "btn_plan_7d": "⭐ 7 Days — 20 XTR",
        "btn_plan_1m": "⭐ 1 Month — 50 XTR",
        "btn_plan_3m": "⭐ 3 Months — 120 XTR",
        "btn_plan_life": "⭐ Lifetime — 350 XTR",
        "plan_1d_title": "Onward Premium (1 Day)",
        "plan_7d_title": "Onward Premium (7 Days)",
        "plan_1m_title": "Onward Premium (1 Month)",
        "plan_3m_title": "Onward Premium (3 Months)",
        "plan_life_title": "Onward Premium (Lifetime)",
        "invoice_desc": "Premium access for channel {channel_id}",
        "pay_success": "🎉 <b>Payment successful!</b>\n\n<b>Onward Premium</b> status is now active for channel <code>{channel_id}</code>.\nThank you for supporting the project!"
    },

    "hi": {
        "sub_menu_header": "📢 <b>канал के लिए सुझाव पेटी {channel_title}</b>\n{rating_str}\nनीचे एक विकल्प चुनें:",
        "rating_line": "⭐ <b>रेटिंग:</b> {avg_rating} / 5.0 ({count} समीक्षाएं)\n",
        "btn_idea": "💡 विचार सुझाव दें",
        "btn_question_all": "❓ मालिकों से सवाल पूछें",
        "btn_question_admin": "👤 विशिष्ट एडमिन से पूछें",
        "btn_review": "⭐ समीक्षा और रेटिंग दें",
        "choose_anonymity": "आप यह संदेश कैसे भेजना चाहते हैं?",
        "btn_anon": "🕵️ गुमनाम (Anonymous)",
        "btn_public": "👤 सार्वजनिक (@{username})",
        "prompt_send_idea": "💡 अपना विचार लिखें या मीडिया भेजें:",
        "prompt_send_question": "❓ अपना प्रश्न लिखें:",
        "prompt_select_rating": "⭐ 1 से 5 स्टार तक रेट करें:",
        "prompt_send_review_text": "✍️ एक टिप्पणी लिखें (या स्किप करें):",
        "btn_skip": "⏩ छोड़ें (Skip)",
        "msg_sent_success": "✅ आपका संदेश एडमिन को भेज दिया गया है!",
        "review_saved_success": "🎉 आपकी समीक्षा के लिए धन्यवाद!",
        "review_cooldown_error": "⏳ आप पहले ही समीक्षा दे चुके हैं। {days_left} दिनों में अपडेट कर सकते हैं।",
        "user_banned_error": "🛑 एडमिन ने आपको संदेश भेजने से प्रतिबंधित कर दिया है।",
        "err_channel_not_found_subscriber": "❌ चैनल नहीं मिला या लिंक अमान्य है।",
        "prompt_choose_admin": "प्रश्न पूछने के लिए एक एडमिन चुनें:",
        "media_placeholder": "[मीडिया फ़ाइल]",
        "admin_card_processed": "📥 <b>प्रोसेस हो गया</b>\n❓ <b>प्रश्न:</b> <i>«{orig_text}»</i>\n\n✅ <b>एडमिन {actor_name} ({action_str}):</b>\n<i>«{answer_text}»</i>",
        "action_priv_reply": "निजी उत्तर दिया",
        "action_pub_reply": "चैनल में उत्तर दिया",
        "action_published_idea": "विचार प्रकाशित किया",
        "anon_question_title": "❓ <b>गुमनाम प्रश्न</b>",
        "public_question_title_open": "❓ <b>{author_str} का प्रश्न</b>",
        "idea_post_header_anon": "💡 <b>सब्सक्राइबर का विचार</b>",
        "idea_post_header_public": "💡 <b>{author_str} का विचार</b>",
        "channel_reply_header": "💬 <b>उत्तर:</b>",
        "channel_ask_prompt": "🤖 <i>अपना प्रश्न पूछें: {bot_link}</i>",
        "idea_suggest_prompt": "🤖 <i>अपना विचार सुझाएं: {bot_link}</i>",
        "btn_reply_private": "💬 निजी उत्तर दें",
        "btn_reply_public": "📢 चैनल पर उत्तर दें",
        "btn_publish_idea": "🚀 चैनल में प्रकाशित करें",
        "btn_ban_user": "🚫 ब्लॉक करें",
        "btn_unban_user": "🔄 अनब्लॉक करें",
        "btn_back": "🔙 वापस",
        "admin_welcome_no_channels": "👋 <b>Onward में आपका स्वागत है!</b>",
        "admin_panel_welcome": "⚙️ <b>Onward कंट्रोल पैनल</b>",
        "admin_channel_manage": "📢 <b>चैनल प्रबंधन «{ch_title}»</b>",
        "status_premium": "⭐ प्रीमियम",
        "status_free": "🆓 मुफ्त",
        "btn_set_btns": "⚙️ बटन सेटिंग्स",
        "btn_set_profile": "👤 मेरी प्रोफाइल",
        "btn_add_coadmin": "👥 एडमिन जोड़ें",
        "btn_ban_list": "🚫 प्रतिबंधित उपयोगकर्ता",
        "btn_premium": "⭐ Onward प्रीमियम",
        "btn_manage_premium": "⭐ ऑनवर्ड प्रीमियम सेटिंग्स",
        "premium_settings_header": "⭐ <b>प्रीमियम सेटिंग्स:</b>",
        "btn_set_welcome": "🎨 कस्टम स्वागत संदेश",
        "btn_set_autoreply": "🤖 स्वचालित उत्तर",
        "btn_copyright_on": "✅ बॉट हस्ताक्षर चालू",
        "btn_copyright_off": "❌ बॉट हस्ताक्षर बंद",
        "prompt_enter_welcome": "🎨 नया स्वागत संदेश दर्ज करें:",
        "welcome_saved_success": "✅ सहेजा गया!",
        "welcome_reset_success": "🔄 रीसेट!",
        "prompt_enter_autoreply": "🤖 ऑटो-रिप्लाई दर्ज करें:",
        "autoreply_saved_success": "✅ सहेजा गया!",
        "autoreply_reset_success": "🔄 बंद किया गया!",
        "btn_reset": "🔄 रीसेट",
        "btn_back_channels": "🔙 वापस",
        "header_set_btns": "⚙️ <b>बटन सेटिंग्स:</b>",
        "header_set_profile": "👤 <b>प्रोफ़ाइल सेटिंग्स:</b>",
        "btn_accepts_on": "✅ सीधे प्रश्न स्वीकार करें",
        "btn_accepts_off": "❌ सीधे प्रश्न स्वीकार न करें",
        "disp_anon_title": "एडमिन #X",
        "disp_name_title": "नाम",
        "disp_username_title": "@username",
        "btn_unban_id": "🔓 अनब्लॉक (ID: {user_id})",
        "coadmin_text": "👥 <b>लिंक:</b>\n<code>{inv_link}</code>",
        "ban_list_empty": "🎉 कोई ब्लॉक यूजर नहीं है।",
        "ban_list_header": "🚫 <b>ब्लॉक यूजर:</b>",
        "toast_unbanned": "✅ अनब्लॉक कर दिया गया!",
        "premium_menu_text": "⭐ <b>Onward प्रीमियम</b>",
        "btn_plan_1d": "⭐ 1 दिन — 5 XTR",
        "btn_plan_7d": "⭐ 7 दिन — 20 XTR",
        "btn_plan_1m": "⭐ 1 महीना — 50 XTR",
        "btn_plan_3m": "⭐ 3 महीने — 120 XTR",
        "btn_plan_life": "⭐ लाइफटाइम — 350 XTR",
        "plan_1d_title": "Onward प्रीमियम (1 दिन)",
        "plan_7d_title": "Onward प्रीमियम (7 दिन)",
        "plan_1m_title": "Onward प्रीमियम (1 महीना)",
        "plan_3m_title": "Onward प्रीमियम (3 महीने)",
        "plan_life_title": "Onward प्रीमियम (लाइफ टाइम)",
        "invoice_desc": "चैनल के लिए प्रीमियम पहुंच {channel_id}",
        "pay_success": "🎉 <b>भुगतान सफल रहा!</b>"
    },

    "es": {
        "sub_menu_header": "📢 <b>Sugerencias para {channel_title}</b>\n{rating_str}\nElige una opción:",
        "rating_line": "⭐ <b>Calificación:</b> {avg_rating} / 5.0 ({count} reseñas)\n",
        "btn_idea": "💡 Sugerir una idea",
        "btn_question_all": "❓ Preguntar a los dueños",
        "btn_question_admin": "👤 Preguntar a un admin",
        "btn_review": "⭐ Dejar reseña y valoración",
        "choose_anonymity": "¿Cómo quieres enviar este mensaje?",
        "btn_anon": "🕵️ Anónimo",
        "btn_public": "👤 Público (@{username})",
        "prompt_send_idea": "💡 Escribe tu idea o envía contenido multimedia:",
        "prompt_send_question": "❓ Escribe tu pregunta:",
        "prompt_select_rating": "⭐ Califica el canal de 1 a 5 estrellas:",
        "prompt_send_review_text": "✍️ Escribe un comentario corto (o pulsa Omitir):",
        "btn_skip": "⏩ Omitir",
        "msg_sent_success": "✅ ¡Tu mensaje ha sido enviado a los administradores!",
        "review_saved_success": "🎉 ¡Gracias por tu reseña!",
        "review_cooldown_error": "⏳ Ya dejaste una reseña. Podrás actualizarla en {days_left} días.",
        "user_banned_error": "🛑 La administración te ha restringido el envío de mensajes.",
        "err_channel_not_found_subscriber": "❌ Canal no encontrado o enlace expirado.",
        "prompt_choose_admin": "Elige un administrador para hacer tu pregunta:",
        "media_placeholder": "[Archivo Multimedia]",
        "admin_card_processed": "📥 <b>¡Procesado!</b>\n❓ <b>Pregunta:</b> <i>«{orig_text}»</i>\n\n✅ <b>Admin {actor_name} ({action_str}):</b>\n<i>«{answer_text}»</i>",
        "action_priv_reply": "respondió en privado",
        "action_pub_reply": "publicó respuesta en el canal",
        "action_published_idea": "publicó idea en el canal",
        "anon_question_title": "❓ <b>Pregunta anónima</b>",
        "public_question_title_open": "❓ <b>Pregunta de {author_str}</b>",
        "idea_post_header_anon": "💡 <b>Idea de suscriptor</b>",
        "idea_post_header_public": "💡 <b>Idea de {author_str}</b>",
        "channel_reply_header": "💬 <b>Respuesta:</b>",
        "channel_ask_prompt": "🤖 <i>Haz una pregunta o sugiere una idea: {bot_link}</i>",
        "idea_suggest_prompt": "🤖 <i>Sugiere una idea: {bot_link}</i>",
        "btn_reply_private": "💬 Responder en privado",
        "btn_reply_public": "📢 Publicar respuesta en canal",
        "btn_publish_idea": "🚀 Publicar en el canal",
        "btn_ban_user": "🚫 Bloquear usuario",
        "btn_unban_user": "🔄 Desbloquear",
        "btn_back": "🔙 Volver",
        "admin_welcome_no_channels": "👋 <b>¡Bienvenido a Onward!</b>",
        "admin_panel_welcome": "⚙️ <b>Panel de control Onward</b>",
        "admin_channel_manage": "📢 <b>Gestión del canal «{ch_title}»</b>",
        "status_premium": "⭐ Premium",
        "status_free": "🆓 Gratis",
        "btn_set_btns": "⚙️ Ajustes de botones",
        "btn_set_profile": "👤 Mi perfil de admin",
        "btn_add_coadmin": "👥 Añadir co-admin",
        "btn_ban_list": "🚫 Usuarios bloqueados",
        "btn_premium": "⭐ Onward Premium",
        "btn_manage_premium": "⭐ Ajustes Onward Premium",
        "premium_settings_header": "⭐ <b>Ajustes Premium:</b>",
        "btn_set_welcome": "🎨 Bienvenida personalizada",
        "btn_set_autoreply": "🤖 Auto-respuesta personalizada",
        "btn_copyright_on": "✅ Firma del bot activa",
        "btn_copyright_off": "❌ Firma del bot oculta",
        "prompt_enter_welcome": "🎨 Introduce un nuevo mensaje de bienvenida:",
        "welcome_saved_success": "✅ ¡Mensaje guardado!",
        "welcome_reset_success": "🔄 ¡Restablecido!",
        "prompt_enter_autoreply": "🤖 Introduce un mensaje de auto-respuesta:",
        "autoreply_saved_success": "✅ ¡Auto-respuesta guardada!",
        "autoreply_reset_success": "🔄 ¡Desactivada!",
        "btn_reset": "🔄 Restablecer",
        "btn_back_channels": "🔙 Volver a la lista",
        "header_set_btns": "⚙️ <b>Ajustes de botones:</b>",
        "header_set_profile": "👤 <b>Ajustes de perfil:</b>",
        "btn_accepts_on": "✅ Aceptar preguntas directas",
        "btn_accepts_off": "❌ No aceptar preguntas directas",
        "disp_anon_title": "Admin #X",
        "disp_name_title": "Nombre",
        "disp_username_title": "@username",
        "btn_unban_id": "🔓 Desbloquear (ID: {user_id})",
        "coadmin_text": "👥 <b>Enlace:</b>\n<code>{inv_link}</code>",
        "ban_list_empty": "🎉 No hay usuarios bloqueados.",
        "ban_list_header": "🚫 <b>Usuarios bloqueados:</b>",
        "toast_unbanned": "✅ ¡Usuario desbloqueado!",
        "premium_menu_text": "⭐ <b>Onward Premium</b>",
        "btn_plan_1d": "⭐ 1 Día — 5 XTR",
        "btn_plan_7d": "⭐ 7 Días — 20 XTR",
        "btn_plan_1m": "⭐ 1 Mes — 50 XTR",
        "btn_plan_3m": "⭐ 3 Meses — 120 XTR",
        "btn_plan_life": "⭐ Para siempre — 350 XTR",
        "plan_1d_title": "Onward Premium (1 Día)",
        "plan_7d_title": "Onward Premium (7 Días)",
        "plan_1m_title": "Onward Premium (1 Mes)",
        "plan_3m_title": "Onward Premium (3 Meses)",
        "plan_life_title": "Onward Premium (Para siempre)",
        "invoice_desc": "Acceso premium para el canal {channel_id}",
        "pay_success": "🎉 <b>¡Pago exitoso!</b>"
    }
}


def t(key: str, lang: str = "ru", **kwargs) -> str:
    lang_dict = TEXTS.get(lang, TEXTS["en"])
    text_template = lang_dict.get(key) or TEXTS["en"].get(key, key)
    if kwargs:
        try:
            return text_template.format(**kwargs)
        except KeyError:
            return text_template
    return text_template