from typing import Dict

TEXTS: Dict[str, Dict[str, str]] = {
    "ru": {
        # Подписчики
        "sub_menu_header": "📢 <b>Предложка канала {channel_title}</b>\n{rating_str}\nВыберите действие ниже:",
        "rating_line": "⭐ <b>Рейтинг:</b> {avg_rating} / 5.0 ({count} оценок)\n",
        "btn_idea": "💡 Предложить идею",
        "btn_question_all": "❓ Задать вопрос владельцам",
        "btn_question_admin": "👤 Вопрос конкретному админу",
        "btn_review": "⭐ Оставить отзыв и оценку",
        "choose_anonymity": "Как вы хотите отправить сообщение?",
        "btn_anon": "🕵️ Анонимно",
        "btn_public": "👤 Открыто (@{username})",
        "prompt_send_idea": "💡 Напишите вашу идею или отправьте медиафайл (фото/видео/голосовое):",
        "prompt_send_question": "❓ Напишите ваш вопрос (можно прикрепить медиафайл):",
        "prompt_select_rating": "⭐ Выберите вашу оценку каналу от 1 до 5 звезд:",
        "prompt_send_review_text": "✍️ Напишите краткий комментарий к вашей оценке (или нажмите «Пропустить»):",
        "btn_skip": "⏩ Пропустить",
        "msg_sent_success": "✅ Ваше сообщение успешно отправлено администраторам!",
        "review_saved_success": "🎉 Спасибо за ваш отзыв! Оценка сохранена.",
        "review_cooldown_error": "⏳ Вы уже оставляли отзыв. Изменить его можно будет через {days_left} дн.",
        "user_banned_error": "🛑 Администрация канала ограничила вам доступ к отправке сообщений.",
        "err_channel_not_found_subscriber": "❌ Канал не найден или ссылка устарела.",
        "prompt_choose_admin": "Выберите администратора, которому хотите задать вопрос:",
        "media_placeholder": "[Медиафайл]",
        "subscriber_fallback_name": "Подписчик",
        "err_delivery_failed_admin_not_started": "⚠️ <b>Не удалось доставить сообщение!</b>\nАдминистратор еще не запустил диалог с ботом в ЛС.",
        "auto_reply_prefix": "🤖 <b>Автоответ канала:</b>",

        # Уведомления админу в ЛС
        "admin_new_idea": "📥 <b>Новое сообщение для канала [{channel_title}]</b>\n📌 <b>Тип:</b> 💡 Идея\n👤 <b>Автор:</b> {sender_info}\n\n💬 {text}",
        "admin_new_question": "📥 <b>Новое сообщение для канала [{channel_title}]</b>\n📌 <b>Тип:</b> ❓ Вопрос\n👤 <b>Автор:</b> {sender_info}\n\n💬 {text}",
        "admin_new_review": "⭐ <b>Новый отзыв для канала [{channel_title}]</b>\n<b>Оценка:</b> {stars}\n<b>Комментарий:</b> {text}",
        "admin_reply_priv_prompt": "💬 Введите текст личного ответа для подписчика:",
        "admin_reply_pub_prompt": "📢 Введите текст ответа, который будет опубликован в канале:",
        "sub_received_priv_reply": "💬 <b>Ответ от администрации канала [{channel_title}]:</b>\n\n{text}",
        "sub_published_in_channel": "🎉 Ваш вопрос и ответ на него были опубликованы в канале!",
        "sub_idea_published": "🎉 Ваша идея была опубликована в канале!",
        "reply_sent_to_user_success": "✅ Ваш ответ успешно доставлен подписчику!",
        "post_published_success": "✅ Пост успешно опубликован в канале!",
        "card_banned_text": "🛑 Пользователь заблокирован в этом канале.",
        "err_msg_not_found": "❌ Сообщение не найдено.",
        "err_cant_reply": "❌ Не удалось отправить ответ. Возможно, подписчик заблокировал бота.",
        "err_publish_failed": "❌ Ошибка при публикации в канал: {error}",
        "admin_card_processed": "📥 <b>Вопрос обработан</b>\n❓ <b>Вопрос:</b> <i>«{orig_text}»</i>\n\n✅ <b>{actor_name} ({action_str}):</b>\n<i>«{answer_text}»</i>",
        "admin_name_fmt": "Админ {name}",
        "admin_username_fmt": "Админ {username}",
        "action_priv_reply": "ответил лично",
        "action_pub_reply": "ответил в канал",
        "action_published_idea": "опубликовал идею в канал",

        # Кнопки админа
        "btn_reply_private": "💬 Ответить лично",
        "btn_reply_public": "📢 Публичный ответ в канал",
        "btn_publish_idea": "🚀 Опубликовать в канал",
        "btn_ban_user": "🚫 Заблокировать",
        "btn_unban_user": "🔄 Разблокировать",
        "btn_back": "🔙 Назад",

        # Шаблоны публикаций в канале
        "anon_question_title": "❓ <b>Анонимный вопрос</b>",
        "public_question_title_open": "❓ <b>Вопрос от {author_str}</b>",
        "channel_reply_header": "💬 <b>Ответ:</b>",
        "channel_ask_prompt": "🤖 <i>Задать свой вопрос: {bot_link}</i>",
        "idea_post_header_anon": "💡 <b>Пост от подписчика</b>",
        "idea_post_header_public": "💡 <b>Пост от {author_str}</b>",
        "idea_suggest_prompt": "🤖 <i>Предложить свою идею: {bot_link}</i>",

        # Регистрация канала
        "channel_setup_success": "🎉 <b>Канал «{channel_title}» успешно подключен!</b>\n\n🔗 Ваша уникальная ссылка предложки для подписчиков:\n<code>{sub_link}</code>\n\nРазместите эту ссылку в описании канала или в постах!",
        "channel_setup_temp_post": "⚙️ <b>Настройка Onward:</b> Администратору нужно нажать кнопку ниже для завершения подключения:",
        "btn_complete_setup": "🔗 Завершить настройку Onward",
        "bot_removed_from_channel": "⚠️ Бот Onward был удален из канала. Прием сообщений временно приостановлен.",
        "err_not_channel_admin": "❌ Ошибка: Вы не являетесь администратором этого канала.",
        "err_check_rights_failed": "❌ Не удалось проверить права. Убедитесь, что бот добавлен в канал.",
        "reg_success": "🎉 <b>Регистрация завершена!</b>\n\n🔗 Ссылка предложки для вашего канала:\n<code>{sub_link}</code>",
        "err_inv_not_admin": "❌ Ошибка: Чтобы стать админом бота, вы должны сначала стать админом канала в Telegram.",
        "err_channel_not_found": "❌ Канал не найден или бот из него удален.",
        "coadmin_registered_success": "✅ Вы успешно зарегистрированы как администратор этого канала в Onward!",
        "coadmin_already_registered": "ℹ️ Вы уже являетесь администратором этого канала в боте.",

        # Админ Панель
        "admin_welcome_no_channels": "👋 <b>Добро пожаловать в Onward!</b>\n\nЧтобы начать, добавьте меня в свой Telegram-канал как администратора. Я автоматически сгенерирую ссылку предложки для ваших подписчиков!",
        "admin_panel_welcome": "⚙️ <b>Панель управления Onward</b>\nВыберите канал для настройки:",
        "admin_channel_manage": "📢 <b>Управление каналом «{ch_title}»</b>\nСтатус: {status}\n\n🔗 <b>Ссылка предложки:</b>\n<code>{sub_link}</code>",
        "status_premium": "⭐ Premium",
        "status_free": "🆓 Free",
        "btn_set_btns": "⚙️ Настройки кнопок",
        "btn_set_profile": "👤 Мой профиль админа",
        "btn_add_coadmin": "👥 Добавить со-админа",
        "btn_ban_list": "🚫 Заблокированные юзеры",
        "btn_premium": "⭐ Onward Premium",
        "btn_back_channels": "🔙 Назад к списку",
        "header_set_btns": "⚙️ <b>Настройки отображения кнопок для подписчиков:</b>",
        "header_set_profile": "👤 <b>Настройки отображения вашего профиля в предложке:</b>",
        "btn_accepts_on": "✅ Принимать личные вопросы",
        "btn_accepts_off": "❌ Не принимать личные вопросы",
        "disp_anon_title": "Админ №X",
        "disp_name_title": "Имя",
        "disp_username_title": "@username",
        "btn_unban_id": "🔓 Разблокировать (ID: {user_id})",
        "coadmin_text": "👥 <b>Ссылка для добавления со-админа:</b>\n<code>{inv_link}</code>\n\nПерешлите эту ссылку второму администратору. Он должен быть администратором вашего канала в Telegram.",
        "ban_list_empty": "🎉 В этом канале нет заблокированных пользователей.",
        "ban_list_header": "🚫 <b>Заблокированные пользователи канала:</b>",
        "toast_unbanned": "✅ Пользователь успешно разблокирован!",

        # Премиум настройки
        "btn_manage_premium": "⭐ Настройки Onward Premium",
        "premium_settings_header": "⭐ <b>Настройки Onward Premium:</b>",
        "btn_set_welcome": "🎨 Кастомное приветствие",
        "btn_set_autoreply": "🤖 Кастомный автоответ",
        "btn_copyright_on": "✅ Подпись бота под постами",
        "btn_copyright_off": "❌ Подпись бота скрыта",
        "prompt_enter_welcome": "🎨 Введите новый текст приветствия, который увидят подписчики при входе в предложку:",
        "welcome_saved_success": "✅ Кастомное приветствие сохранено!",
        "welcome_reset_success": "🔄 Приветствие сброшено к стандартному.",
        "prompt_enter_autoreply": "🤖 Введите текст автоответа, который получит подписчик сразу после отправки сообщения:",
        "autoreply_saved_success": "✅ Автоответ успешно сохранен!",
        "autoreply_reset_success": "🔄 Автоответ отключен.",
        "btn_ch_lang": "🌐 Язык публикаций: {curr_lang}",
        "header_ch_lang": "🌐 <b>Выберите язык для постов и ответов в канале:</b>\n\nВсе публичные вопросы и идеи в вашем канале будут выходить на выбранном языке.",
        "prompt_choose_user_lang": "🌐 <b>Выберите ваш личный язык интерфейса бота:</b>",
        "toast_user_lang_updated": "✅ Язык интерфейса успешно обновлен!",
        "toast_ch_lang_updated": "✅ Язык публикаций канала успешно обновлен!",
        "btn_reset": "🔄 Сбросить",
        "btn_channel_stats": "📊 Статистика и экспорт",
        "stats_menu_text": "📊 <b>Статистика канала «{ch_title}»:</b>\n\n💡 <b>Предложено идей:</b> {ideas_count}\n❓ <b>Задано вопросов:</b> {questions_count}\n⭐ <b>Всего отзывов:</b> {reviews_count}\n📈 <b>Средний рейтинг:</b> {rating_avg} / 5.0\n✅ <b>Обработано сообщений:</b> {processed_count}",
        "btn_export_csv": "📥 Скачать отзывы в CSV",
        "err_no_reviews_export": "ℹ️ У канала пока нет отзывов для экспорта.",
        "csv_file_caption": "📊 Выгрузка всех отзывов канала «{ch_title}»",

        # Оплата Stars
        "premium_menu_text": "⭐ <b>Onward Premium</b>\n\nПодключите Premium и откройте продвинутые возможности для канала:\n• 🎨 Кастомное приветствие и правила\n• 🤖 Настройка автоответа подписчикам\n• 🚫 Отключение копирайта бота\n• 📊 Подробная статистика и экспорт\n\nВыберите тариф для оплаты Звёздами Telegram:",
        "btn_plan_1d": "⭐ 1 День — 5 XTR",
        "btn_plan_7d": "⭐ 7 Дней — 20 XTR",
        "btn_plan_1m": "⭐ 1 Месяц — 50 XTR",
        "btn_plan_3m": "⭐ 3 Месяца — 120 XTR",
        "btn_plan_life": "⭐ Навсегда — 350 XTR",
        "plan_1d_title": "Onward Premium (1 день)",
        "plan_7d_title": "Onward Premium (7 дней)",
        "plan_1m_title": "Onward Premium (1 месяц)",
        "plan_3m_title": "Onward Premium (3 месяца)",
        "plan_life_title": "Onward Premium (Навсегда)",
        "invoice_desc": "Премиум доступ для канала {channel_id}",
        "pay_success": "🎉 <b>Оплата прошла успешно!</b>\n\nДля канала <code>{channel_id}</code> успешно активирован статус <b>Onward Premium</b>.\nСпасибо за поддержку проекта!"
    },

    "en": {
        "sub_menu_header": "📢 <b>Suggestion box for {channel_title}</b>\n{rating_str}\nChoose an action below:",
        "rating_line": "⭐ <b>Rating:</b> {avg_rating} / 5.0 ({count} reviews)\n",
        "btn_idea": "💡 Suggest an idea",
        "btn_question_all": "❓ Ask channel owners",
        "btn_question_admin": "👤 Ask specific admin",
        "btn_review": "⭐ Leave review & rating",
        "choose_anonymity": "How would you like to send this message?",
        "btn_anon": "🕵️ Anonymously",
        "btn_public": "👤 Publicly (@{username})",
        "prompt_send_idea": "💡 Type your idea or send media (photo/video/voice):",
        "prompt_send_question": "❓ Type your question (media attachments supported):",
        "prompt_select_rating": "⭐ Rate the channel from 1 to 5 stars:",
        "prompt_send_review_text": "✍️ Write a short comment (or tap Skip):",
        "btn_skip": "⏩ Skip",
        "msg_sent_success": "✅ Your message has been sent to the admins!",
        "review_saved_success": "🎉 Thank you for your review!",
        "review_cooldown_error": "⏳ You have already left a review. You can update it in {days_left} days.",
        "user_banned_error": "🛑 The channel administration has restricted you from sending messages.",
        "err_channel_not_found_subscriber": "❌ Channel not found or link expired.",
        "prompt_choose_admin": "Choose an admin to ask your question:",
        "media_placeholder": "[Media File]",
        "subscriber_fallback_name": "Subscriber",
        "err_delivery_failed_admin_not_started": "⚠️ <b>Message delivery failed!</b>\nThe administrator has not started a DM with the bot yet.",
        "auto_reply_prefix": "🤖 <b>Channel Auto-reply:</b>",

        "admin_new_idea": "📥 <b>New message for [{channel_title}]</b>\n📌 <b>Type:</b> 💡 Idea\n👤 <b>Author:</b> {sender_info}\n\n💬 {text}",
        "admin_new_question": "📥 <b>New message for [{channel_title}]</b>\n📌 <b>Type:</b> ❓ Question\n👤 <b>Author:</b> {sender_info}\n\n💬 {text}",
        "admin_new_review": "⭐ <b>New review for [{channel_title}]</b>\n<b>Rating:</b> {stars}\n<b>Comment:</b> {text}",
        "admin_reply_priv_prompt": "💬 Enter text for private reply to subscriber:",
        "admin_reply_pub_prompt": "📢 Enter text for public reply to be posted in channel:",
        "sub_received_priv_reply": "💬 <b>Reply from [{channel_title}] administration:</b>\n\n{text}",
        "sub_published_in_channel": "🎉 Your question and answer have been published in the channel!",
        "sub_idea_published": "🎉 Your idea has been published in the channel!",
        "reply_sent_to_user_success": "✅ Your reply was successfully delivered to subscriber!",
        "post_published_success": "✅ Post successfully published in channel!",
        "card_banned_text": "🛑 User banned in this channel.",
        "err_msg_not_found": "❌ Message not found.",
        "err_cant_reply": "❌ Could not send reply. The subscriber may have blocked the bot.",
        "err_publish_failed": "❌ Publishing error: {error}",
        "admin_card_processed": "📥 <b>Message processed</b>\n❓ <b>Question:</b> <i>«{orig_text}»</i>\n\n✅ <b>{actor_name} ({action_str}):</b>\n<i>«{answer_text}»</i>",
        "admin_name_fmt": "Admin {name}",
        "admin_username_fmt": "Admin {username}",
        "action_priv_reply": "replied privately",
        "action_pub_reply": "posted reply to channel",
        "action_published_idea": "published idea to channel",

        "btn_reply_private": "💬 Reply privately",
        "btn_reply_public": "📢 Post reply to channel",
        "btn_publish_idea": "🚀 Publish to channel",
        "btn_ban_user": "🚫 Ban user",
        "btn_unban_user": "🔄 Unban user",
        "btn_back": "🔙 Back",

        "anon_question_title": "❓ <b>Anonymous Question</b>",
        "public_question_title_open": "❓ <b>Question from {author_str}</b>",
        "channel_reply_header": "💬 <b>Answer:</b>",
        "channel_ask_prompt": "🤖 <i>Ask a question or suggest an idea: {bot_link}</i>",
        "idea_post_header_anon": "💡 <b>Subscriber Idea</b>",
        "idea_post_header_public": "💡 <b>Idea from {author_str}</b>",
        "idea_suggest_prompt": "🤖 <i>Suggest an idea: {bot_link}</i>",

        "channel_setup_success": "🎉 <b>Channel «{channel_title}» successfully connected!</b>\n\n🔗 Your unique suggestion link for subscribers:\n<code>{sub_link}</code>\n\nPlace this link in your channel description or posts!",
        "channel_setup_temp_post": "⚙️ <b>Onward Setup:</b> The administrator needs to press the button below to complete setup:",
        "btn_complete_setup": "🔗 Complete Onward Setup",
        "bot_removed_from_channel": "⚠️ The Onward bot was removed from the channel. Receiving messages paused.",
        "err_not_channel_admin": "❌ Error: You are not an administrator of this channel.",
        "err_check_rights_failed": "❌ Could not verify permissions. Ensure the bot is added to the channel.",
        "reg_success": "🎉 <b>Registration complete!</b>\n\n🔗 Suggestion link for your channel:\n<code>{sub_link}</code>",
        "err_inv_not_admin": "❌ Error: To become a bot admin, you must first be an admin of the channel in Telegram.",
        "err_channel_not_found": "❌ Channel not found or bot was removed.",
        "coadmin_registered_success": "✅ You have been successfully registered as a channel admin in Onward!",
        "coadmin_already_registered": "ℹ️ You are already registered as an admin for this channel.",

        "admin_welcome_no_channels": "👋 <b>Welcome to Onward!</b>\n\nTo start, add me as an administrator to your Telegram channel. I will automatically generate a suggestion box link for your subscribers!",
        "admin_panel_welcome": "⚙️ <b>Onward Control Panel</b>\nSelect a channel to configure:",
        "admin_channel_manage": "📢 <b>Channel Management «{ch_title}»</b>\nStatus: {status}\n\n🔗 <b>Suggestion link:</b>\n<code>{sub_link}</code>",
        "status_premium": "⭐ Premium",
        "status_free": "🆓 Free",
        "btn_set_btns": "⚙️ Button settings",
        "btn_set_profile": "👤 My admin profile",
        "btn_add_coadmin": "👥 Add co-admin",
        "btn_ban_list": "🚫 Banned users",
        "btn_premium": "⭐ Onward Premium",
        "btn_back_channels": "🔙 Back to list",
        "header_set_btns": "⚙️ <b>Button display settings for subscribers:</b>",
        "header_set_profile": "👤 <b>Your profile display settings:</b>",
        "btn_accepts_on": "✅ Accept direct questions",
        "btn_accepts_off": "❌ Do not accept direct questions",
        "disp_anon_title": "Admin #X",
        "disp_name_title": "Name",
        "disp_username_title": "@username",
        "btn_unban_id": "🔓 Unban (ID: {user_id})",
        "coadmin_text": "👥 <b>Link to add a co-admin:</b>\n<code>{inv_link}</code>\n\nForward this link to another administrator. They must be an admin of your Telegram channel.",
        "ban_list_empty": "🎉 There are no banned users in this channel.",
        "ban_list_header": "🚫 <b>Banned users for this channel:</b>",
        "toast_unbanned": "✅ User successfully unbanned!",

        "btn_manage_premium": "⭐ Onward Premium Settings",
        "premium_settings_header": "⭐ <b>Onward Premium Settings:</b>",
        "btn_set_welcome": "🎨 Custom Welcome Message",
        "btn_set_autoreply": "🤖 Custom Auto-reply",
        "btn_copyright_on": "✅ Bot copyright enabled",
        "btn_copyright_off": "❌ Bot copyright hidden",
        "prompt_enter_welcome": "🎨 Enter a new welcome message for subscribers:",
        "welcome_saved_success": "✅ Custom welcome message saved!",
        "welcome_reset_success": "🔄 Welcome message reset to default.",
        "prompt_enter_autoreply": "🤖 Enter an auto-reply message sent to subscribers after submission:",
        "autoreply_saved_success": "✅ Auto-reply saved!",
        "autoreply_reset_success": "🔄 Auto-reply disabled.",
        "btn_ch_lang": "🌐 Channel Language: {curr_lang}",
        "header_ch_lang": "🌐 <b>Select language for posts in channel:</b>\n\nAll public questions and ideas in your channel will be published in this language.",
        "prompt_choose_user_lang": "🌐 <b>Select your interface language for the bot:</b>",
        "toast_user_lang_updated": "✅ Interface language updated successfully!",
        "toast_ch_lang_updated": "✅ Channel language updated successfully!",
        "btn_reset": "🔄 Reset",
        "btn_channel_stats": "📊 Analytics & CSV Export",
        "stats_menu_text": "📊 <b>Statistics for «{ch_title}»:</b>\n\n💡 <b>Ideas suggested:</b> {ideas_count}\n❓ <b>Questions asked:</b> {questions_count}\n⭐ <b>Total reviews:</b> {reviews_count}\n📈 <b>Average rating:</b> {rating_avg} / 5.0\n✅ <b>Processed messages:</b> {processed_count}",
        "btn_export_csv": "📥 Download Reviews CSV",
        "err_no_reviews_export": "ℹ️ No reviews available for export yet.",
        "csv_file_caption": "📊 Review export for channel «{ch_title}»",

        "premium_menu_text": "⭐ <b>Onward Premium</b>\n\nUnlock advanced features for your channel:\n• 🎨 Custom welcome & rules\n• 🤖 Custom auto-replies\n• 🚫 Remove bot branding\n• 📊 Detailed analytics & export\n\nChoose a plan using Telegram Stars:",
        "btn_plan_1d": "⭐ 1 Day — 5 XTR",
        "btn_plan_7d": "⭐ 7 Days — 20 XTR",
        "btn_plan_1m": "⭐ 1 Month — 50 XTR",
        "btn_plan_3m": "⭐ 3 Months — 120 XTR",
        "btn_plan_life": "⭐ Lifetime — 350 XTR",
        "plan_1d_title": "Onward Premium (1 Day)",
        "plan_7d_title": "Onward Premium (7 Days)",
        "plan_1m_title": "Onward Premium (1 Month)",
        "plan_3m_title": "Onward Premium (3 Months)",
        "plan_life_title": "Onward Premium (Lifetime)",
        "invoice_desc": "Premium access for channel {channel_id}",
        "pay_success": "🎉 <b>Payment successful!</b>\n\n<b>Onward Premium</b> status is now active for channel <code>{channel_id}</code>.\nThank you for supporting the project!"
    },

    "hi": {
        "sub_menu_header": "📢 <b>चैनल {channel_title} की सुझाव पेटी</b>\n{rating_str}\nनीचे एक कार्रवाई चुनें:",
        "rating_line": "⭐ <b>रेटिंग:</b> {avg_rating} / 5.0 ({count} समीक्षाएं)\n",
        "btn_idea": "💡 विचार का सुझाव दें",
        "btn_question_all": "❓ मालिकों से सवाल पूछें",
        "btn_question_admin": "👤 किसी विशेष एडमिन से पूछें",
        "btn_review": "⭐ समीक्षा और रेटिंग दें",
        "choose_anonymity": "आप यह संदेश कैसे भेजना चाहते हैं?",
        "btn_anon": "🕵️ गुमनाम (Anonymously)",
        "btn_public": "👤 सार्वजनिक (@{username})",
        "prompt_send_idea": "💡 अपना विचार लिखें या मीडिया भेजें (फ़ोटो/वीडियो/वॉयस):",
        "prompt_send_question": "❓ अपना प्रश्न लिखें (मीडिया संलग्नक समर्थित हैं):",
        "prompt_select_rating": "⭐ चैनल को 1 से 5 स्टार रेटिंग दें:",
        "prompt_send_review_text": "✍️ अपनी रेटिंग पर एक संक्षिप्त टिप्पणी लिखें (या 'स्किप' दबाएं):",
        "btn_skip": "⏩ छोड़ें (Skip)",
        "msg_sent_success": "✅ आपका संदेश एडमिन को सफलतापूर्वक भेज दिया गया है!",
        "review_saved_success": "🎉 आपकी समीक्षा के लिए धन्यवाद! रेटिंग सहेज ली गई है।",
        "review_cooldown_error": "⏳ आप पहले ही समीक्षा छोड़ चुके हैं। आप इसे {days_left} दिनों में अपडेट कर सकते हैं।",
        "user_banned_error": "🛑 चैनल प्रशासन ने आपको संदेश भेजने से प्रतिबंधित कर दिया है।",
        "err_channel_not_found_subscriber": "❌ चैनल नहीं मिला या लिंक समाप्त हो गया है।",
        "prompt_choose_admin": "प्रश्न पूछने के लिए एक एडमिन चुनें:",
        "media_placeholder": "[मीडिया फ़ाइल]",
        "subscriber_fallback_name": "सब्सक्राइबर",
        "err_delivery_failed_admin_not_started": "⚠️ <b>संदेश वितरण विफल रहा!</b>\nएडमिन ने अभी तक बॉट के साथ निजी बातचीत शुरू नहीं की है।",
        "auto_reply_prefix": "🤖 <b>चैनल का स्वचालित उत्तर:</b>",

        "admin_new_idea": "📥 <b>[{channel_title}] के लिए नया संदेश</b>\n📌 <b>प्रकार:</b> 💡 विचार\n👤 <b>लेखक:</b> {sender_info}\n\n💬 {text}",
        "admin_new_question": "📥 <b>[{channel_title}] के लिए नया संदेश</b>\n📌 <b>प्रकार:</b> ❓ प्रश्न\n👤 <b>लेखक:</b> {sender_info}\n\n💬 {text}",
        "admin_new_review": "⭐ <b>[{channel_title}] के लिए नई समीक्षा</b>\n<b>रेटिंग:</b> {stars}\n<b>टिप्पणी:</b> {text}",
        "admin_reply_priv_prompt": "💬 सब्सक्राइबर के लिए निजी उत्तर का पाठ दर्ज करें:",
        "admin_reply_pub_prompt": "📢 चैनल में प्रकाशित किए जाने वाले उत्तर का पाठ दर्ज करें:",
        "sub_received_priv_reply": "💬 <b>चैनल [{channel_title}] के प्रशासन का उत्तर:</b>\n\n{text}",
        "sub_published_in_channel": "🎉 आपका प्रश्न और उत्तर चैनल में प्रकाशित हो गए हैं!",
        "sub_idea_published": "🎉 आपका विचार चैनल में प्रकाशित हो गया है!",
        "reply_sent_to_user_success": "✅ आपका उत्तर सब्सक्राइबर तक सफलतापूर्वक पहुंचा दिया गया है!",
        "post_published_success": "✅ पोस्ट चैनल में सफलतापूर्वक प्रकाशित हो गई है!",
        "card_banned_text": "🛑 उपयोगकर्ता इस चैनल में अवरुद्ध है।",
        "err_msg_not_found": "❌ संदेश नहीं मिला।",
        "err_cant_reply": "❌ उत्तर नहीं भेजा जा सका। हो सकता है कि सब्सक्राइबर ने बॉट को ब्लॉक कर दिया हो।",
        "err_publish_failed": "❌ चैनल में प्रकाशित करने में त्रुटि: {error}",
        "admin_card_processed": "📥 <b>संदेश संसाधित हो गया!</b>\n❓ <b>प्रश्न:</b> <i>«{orig_text}»</i>\n\n✅ <b>{actor_name} ({action_str}):</b>\n<i>«{answer_text}»</i>",
        "admin_name_fmt": "एडमिन {name}",
        "admin_username_fmt": "एडमिन {username}",
        "action_priv_reply": "निजी उत्तर दिया",
        "action_pub_reply": "चैनल में उत्तर दिया",
        "action_published_idea": "चैनल में विचार प्रकाशित किया",

        "btn_reply_private": "💬 निजी उत्तर दें",
        "btn_reply_public": "📢 चैनल में उत्तर दें",
        "btn_publish_idea": "🚀 चैनल में प्रकाशित करें",
        "btn_ban_user": "🚫 ब्लॉक करें",
        "btn_unban_user": "🔄 अनब्लॉक करें",
        "btn_back": "🔙 वापस",

        "anon_question_title": "❓ <b>गुमनाम प्रश्न</b>",
        "public_question_title_open": "❓ <b>{author_str} का प्रश्न</b>",
        "channel_reply_header": "💬 <b>उत्तर:</b>",
        "channel_ask_prompt": "🤖 <i>प्रश्न पूछें या विचार का सुझाव दें: {bot_link}</i>",
        "idea_post_header_anon": "💡 <b>सब्सक्राइबर का विचार</b>",
        "idea_post_header_public": "💡 <b>{author_str} का विचार</b>",
        "idea_suggest_prompt": "🤖 <i>अपना विचार साझा करें: {bot_link}</i>",

        "channel_setup_success": "🎉 <b>चैनल «{channel_title}» सफलतापूर्वक जोड़ा गया!</b>\n\n🔗 सब्सक्राइबरों के लिए आपका अनूठा सुझाव लिंक:\n<code>{sub_link}</code>\n\nइसे अपने चैनल के विवरण में रखें!",
        "channel_setup_temp_post": "⚙️ <b>Onward सेटअप:</b> सेटअप पूरा करने के लिए व्यवस्थापक को नीचे दिए गए बटन को दबाना होगा:",
        "btn_complete_setup": "🔗 Onward सेटअप पूरा करें",
        "bot_removed_from_channel": "⚠️ Onward बॉट को चैनल से हटा दिया गया है। संदेशों की प्राप्ति रोक दी गई है।",
        "err_not_channel_admin": "❌ त्रुटि: आप इस चैनल के प्रशासक नहीं हैं।",
        "err_check_rights_failed": "❌ अनुमतियों की जांच नहीं की जा सकी। सुनिश्चित करें कि बॉट चैनल में जोड़ा गया है।",
        "reg_success": "🎉 <b>पंजीकरण पूरा हुआ!</b>\n\n🔗 आपके चैनल के लिए सुझाव लिंक:\n<code>{sub_link}</code>",
        "err_inv_not_admin": "❌ त्रुटि: बॉट एडमिन बनने के लिए आपको पहले टेलीग्राम चैनल का एडमिन होना चाहिए।",
        "err_channel_not_found": "❌ चैनल नहीं मिला या बॉट हटा दिया गया।",
        "coadmin_registered_success": "✅ आप Onward में इस चैनल के प्रशासक के रूप में सफलतापूर्वक पंजीकृत हो गए हैं!",
        "coadmin_already_registered": "ℹ️ आप पहले से ही इस चैनल के प्रशासक के रूप में पंजीकृत हैं।",

        "admin_welcome_no_channels": "👋 <b>Onward में आपका स्वागत है!</b>\n\nशुरू करने के लिए, मुझे अपने टेलीग्राम चैनल में प्रशासक के रूप में जोड़ें। मैं स्वचालित रूप से आपके लिए एक सुझाव लिंक उत्पन्न करूंगा!",
        "admin_panel_welcome": "⚙️ <b>Onward कंट्रोल पैनल</b>\nकॉन्फ़िगर करने के लिए एक चैनल चुनें:",
        "admin_channel_manage": "📢 <b>चैनल प्रबंधन «{ch_title}»</b>\nस्थिति: {status}\n\n🔗 <b>सुझाव लिंक:</b>\n<code>{sub_link}</code>",
        "status_premium": "⭐ प्रीमियम",
        "status_free": "🆓 मुफ्त",
        "btn_set_btns": "⚙️ बटन सेटिंग्स",
        "btn_set_profile": "👤 मेरी प्रोफाइल",
        "btn_add_coadmin": "👥 एडमिन जोड़ें",
        "btn_ban_list": "🚫 प्रतिबंधित उपयोगकर्ता",
        "btn_premium": "⭐ Onward प्रीमियम",
        "btn_back_channels": "🔙 सूची पर वापस जाएं",
        "header_set_btns": "⚙️ <b>बटन प्रदर्शन सेटिंग्स:</b>",
        "header_set_profile": "👤 <b>आपकी प्रोफ़ाइल सेटिंग्स:</b>",
        "btn_accepts_on": "✅ सीधे प्रश्न स्वीकार करें",
        "btn_accepts_off": "❌ सीधे प्रश्न स्वीकार न करें",
        "disp_anon_title": "एडमिन #X",
        "disp_name_title": "नाम",
        "disp_username_title": "@username",
        "btn_unban_id": "🔓 अनब्लॉक करें (ID: {user_id})",
        "coadmin_text": "👥 <b>सह-प्रशासक जोड़ने के लिए लिंक:</b>\n<code>{inv_link}</code>\n\nयह लिंक दूसरे प्रशासक को भेजें।",
        "ban_list_empty": "🎉 इस चैनल में कोई ब्लॉक यूजर नहीं है।",
        "ban_list_header": "🚫 <b>इस चैनल के लिए ब्लॉक यूजर:</b>",
        "toast_unbanned": "✅ उपयोगकर्ता को सफलतापूर्वक अनब्लॉक कर दिया गया!",

        "btn_manage_premium": "⭐ ऑनवर्ड प्रीमियम सेटिंग्स",
        "premium_settings_header": "⭐ <b>Onward प्रीमियम सेटिंग्स:</b>",
        "btn_set_welcome": "🎨 कस्टम स्वागत संदेश",
        "btn_set_autoreply": "🤖 कस्टम ऑटो-रिप्लाई",
        "btn_copyright_on": "✅ बॉट वॉटरमार्क चालू",
        "btn_copyright_off": "❌ बॉट वॉटरमार्क छिपा हुआ",
        "prompt_enter_welcome": "🎨 नया स्वागत संदेश दर्ज करें:",
        "welcome_saved_success": "✅ सहेजा गया!",
        "welcome_reset_success": "🔄 डिफ़ॉल्ट पर रीसेट किया गया!",
        "prompt_enter_autoreply": "🤖 नया ऑटो-रिप्लाई संदेश दर्ज करें:",
        "autoreply_saved_success": "✅ सहेजा गया!",
        "autoreply_reset_success": "🔄 ऑटो-रिप्लाई बंद कर दिया गया!",
        "btn_ch_lang": "🌐 चैनल की भाषा: {curr_lang}",
        "header_ch_lang": "🌐 <b>चैनल में पोस्ट की भाषा चुनें:</b>",
        "prompt_choose_user_lang": "🌐 <b>बॉट के लिए अपनी भाषा चुनें:</b>",
        "toast_user_lang_updated": "✅ भाषा अपडेट हो गई!",
        "toast_ch_lang_updated": "✅ चैनल की भाषा अपडेट हो गई!",
        "btn_reset": "🔄 रीसेट",
        "btn_channel_stats": "📊 आंकड़े और CSV निर्यात",
        "stats_menu_text": "📊 <b>«{ch_title}» के आंकड़े:</b>\n\n💡 <b>सुझाए गए विचार:</b> {ideas_count}\n❓ <b>पूछे गए प्रश्न:</b> {questions_count}\n⭐ <b>कुल समीक्षाएं:</b> {reviews_count}\n📈 <b>औसत रेटिंग:</b> {rating_avg} / 5.0\n✅ <b>संसाधित संदेश:</b> {processed_count}",
        "btn_export_csv": "📥 CSV डाउनलोड करें",
        "err_no_reviews_export": "ℹ️ निर्यात के लिए कोई समीक्षा उपलब्ध नहीं है।",
        "csv_file_caption": "📊 «{ch_title}» के लिए समीक्षाएं",

        "premium_menu_text": "⭐ <b>Onward प्रीमियम</b>\n\nप्रीमियम सुविधाएँ अनलॉक करें:\n• 🎨 कस्टम स्वागत और नियम\n• 🤖 स्वचालित उत्तर\n• 🚫 बॉट वॉटरमार्क हटाएं\n• 📊 विस्तृत आंकड़े और निर्यात\n\nटेलीग्राम स्टार्स का उपयोग करके योजना चुनें:",
        "btn_plan_1d": "⭐ 1 दिन — 5 XTR",
        "btn_plan_7d": "⭐ 7 दिन — 20 XTR",
        "btn_plan_1m": "⭐ 1 महीना — 50 XTR",
        "btn_plan_3m": "⭐ 3 महीने — 120 XTR",
        "btn_plan_life": "⭐ लाइफटाइम — 350 XTR",
        "plan_1d_title": "Onward प्रीमियम (1 दिन)",
        "plan_7d_title": "Onward प्रीमियम (7 दिन)",
        "plan_1m_title": "Onward प्रीमियम (1 महीना)",
        "plan_3m_title": "Onward प्रीमियम (3 महीने)",
        "plan_life_title": "Onward प्रीमियम (लाइफ टाइम)",
        "invoice_desc": "चैनल के लिए प्रीमियम पहुंच {channel_id}",
        "pay_success": "🎉 <b>भुगतान सफल रहा!</b>\n\n<b>Onward प्रीमियम</b> चैनल <code>{channel_id}</code> के लिए सक्रिय है।\nसमर्थन के लिए धन्यवाद!"
    },

    "es": {
        "sub_menu_header": "📢 <b>Buzón de sugerencias para {channel_title}</b>\n{rating_str}\nElige una opción a continuación:",
        "rating_line": "⭐ <b>Calificación:</b> {avg_rating} / 5.0 ({count} reseñas)\n",
        "btn_idea": "💡 Sugerir una idea",
        "btn_question_all": "❓ Preguntar a los dueños",
        "btn_question_admin": "👤 Preguntar a un admin",
        "btn_review": "⭐ Dejar reseña y valoración",
        "choose_anonymity": "¿Cómo quieres enviar este mensaje?",
        "btn_anon": "🕵️ Anónimo",
        "btn_public": "👤 Público (@{username})",
        "prompt_send_idea": "💡 Escribe tu idea o envía contenido multimedia (foto/video/voz):",
        "prompt_send_question": "❓ Escribe tu pregunta (archivos multimedia soportados):",
        "prompt_select_rating": "⭐ Califica el canal de 1 a 5 estrellas:",
        "prompt_send_review_text": "✍️ Escribe un comentario corto sobre tu valoración (o pulsa Omitir):",
        "btn_skip": "⏩ Omitir",
        "msg_sent_success": "✅ ¡Tu mensaje ha sido enviado a los administradores!",
        "review_saved_success": "🎉 ¡Gracias por tu reseña! Valoración guardada.",
        "review_cooldown_error": "⏳ Ya dejaste una reseña. Podrás actualizarla en {days_left} días.",
        "user_banned_error": "🛑 La administración del canal te ha restringido el envío de mensajes.",
        "err_channel_not_found_subscriber": "❌ Canal no encontrado o enlace expirado.",
        "prompt_choose_admin": "Elige un administrador para hacer tu pregunta:",
        "media_placeholder": "[Archivo Multimedia]",
        "subscriber_fallback_name": "Suscriptor",
        "err_delivery_failed_admin_not_started": "⚠️ <b>¡Error de entrega del mensaje!</b>\nEl administrador aún no ha iniciado una conversación privada con el bot.",
        "auto_reply_prefix": "🤖 <b>Auto-respuesta del canal:</b>",

        "admin_new_idea": "📥 <b>Nuevo mensaje para [{channel_title}]</b>\n📌 <b>Tipo:</b> 💡 Idea\n👤 <b>Autor:</b> {sender_info}\n\n💬 {text}",
        "admin_new_question": "📥 <b>Nuevo mensaje para [{channel_title}]</b>\n📌 <b>Tipo:</b> ❓ Pregunta\n👤 <b>Autor:</b> {sender_info}\n\n💬 {text}",
        "admin_new_review": "⭐ <b>Nueva reseña para [{channel_title}]</b>\n<b>Calificación:</b> {stars}\n<b>Comentario:</b> {text}",
        "admin_reply_priv_prompt": "💬 Introduce el texto de la respuesta privada para el suscriptor:",
        "admin_reply_pub_prompt": "📢 Introduce el texto de la respuesta para publicar en el canal:",
        "sub_received_priv_reply": "💬 <b>Respuesta de la administración del canal [{channel_title}]:</b>\n\n{text}",
        "sub_published_in_channel": "🎉 ¡Tu pregunta y la respuesta han sido publicadas en el canal!",
        "sub_idea_published": "🎉 ¡Tu idea ha sido publicada en el canal!",
        "reply_sent_to_user_success": "✅ ¡Tu respuesta fue entregada con éxito al suscriptor!",
        "post_published_success": "✅ ¡Publicación realizada con éxito en el canal!",
        "card_banned_text": "🛑 Usuario bloqueado en este canal.",
        "err_msg_not_found": "❌ Mensaje no encontrado.",
        "err_cant_reply": "❌ No se pudo enviar la respuesta. Es posible que el suscriptor haya bloqueado el bot.",
        "err_publish_failed": "❌ Error al publicar en el canal: {error}",
        "admin_card_processed": "📥 <b>¡Mensaje procesado!</b>\n❓ <b>Pregunta:</b> <i>«{orig_text}»</i>\n\n✅ <b>{actor_name} ({action_str}):</b>\n<i>«{answer_text}»</i>",
        "admin_name_fmt": "Admin {name}",
        "admin_username_fmt": "Admin {username}",
        "action_priv_reply": "respondió en privado",
        "action_pub_reply": "publicó respuesta en el canal",
        "action_published_idea": "publicó idea en el canal",

        "btn_reply_private": "💬 Responder en privado",
        "btn_reply_public": "📢 Publicar respuesta en canal",
        "btn_publish_idea": "🚀 Publicar en el canal",
        "btn_ban_user": "🚫 Bloquear usuario",
        "btn_unban_user": "🔄 Desbloquear",
        "btn_back": "🔙 Volver",

        "anon_question_title": "❓ <b>Pregunta anónima</b>",
        "public_question_title_open": "❓ <b>Pregunta de {author_str}</b>",
        "channel_reply_header": "💬 <b>Respuesta:</b>",
        "channel_ask_prompt": "🤖 <i>Haz tu pregunta o sugiere una idea: {bot_link}</i>",
        "idea_post_header_anon": "💡 <b>Idea de suscriptor</b>",
        "idea_post_header_public": "💡 <b>Idea de {author_str}</b>",
        "idea_suggest_prompt": "🤖 <i>Sugiere tu idea: {bot_link}</i>",

        "channel_setup_success": "🎉 <b>¡Canal «{channel_title}» conectado con éxito!</b>\n\n🔗 Tu enlace único de sugerencias para suscriptores:\n<code>{sub_link}</code>\n\n¡Añade este enlace a la descripción o publicaciones de tu canal!",
        "channel_setup_temp_post": "⚙️ <b>Configuración de Onward:</b> El administrador debe pulsar el botón de abajo para completar la configuración:",
        "btn_complete_setup": "🔗 Completar configuración de Onward",
        "bot_removed_from_channel": "⚠️ El bot Onward fue eliminado del canal. Recepción de mensajes pausada.",
        "err_not_channel_admin": "❌ Error: No eres administrador de este canal.",
        "err_check_rights_failed": "❌ No se pudieron verificar los permisos. Asegúrate de añadir el bot al canal.",
        "reg_success": "🎉 <b>¡Registro completado!</b>\n\n🔗 Enlace de sugerencias para tu canal:\n<code>{sub_link}</code>",
        "err_inv_not_admin": "❌ Error: Para ser admin del bot, primero debes ser admin del canal en Telegram.",
        "err_channel_not_found": "❌ Canal no encontrado o bot eliminado.",
        "coadmin_registered_success": "✅ ¡Te has registrado como administrador de este canal en Onward con éxito!",
        "coadmin_already_registered": "ℹ️ Ya estás registrado como administrador de este canal.",

        "admin_welcome_no_channels": "👋 <b>¡Bienvenido a Onward!</b>\n\nPara empezar, añádeme como administrador a tu canal de Telegram. ¡Generaré automáticamente un enlace de sugerencias!",
        "admin_panel_welcome": "⚙️ <b>Panel de control de Onward</b>\nSelecciona un canal para configurar:",
        "admin_channel_manage": "📢 <b>Gestión del canal «{ch_title}»</b>\nEstado: {status}\n\n🔗 <b>Enlace de sugerencias:</b>\n<code>{sub_link}</code>",
        "status_premium": "⭐ Premium",
        "status_free": "🆓 Gratis",
        "btn_set_btns": "⚙️ Ajustes de botones",
        "btn_set_profile": "👤 Mi perfil de admin",
        "btn_add_coadmin": "👥 Añadir co-admin",
        "btn_ban_list": "🚫 Usuarios bloqueados",
        "btn_premium": "⭐ Onward Premium",
        "btn_back_channels": "🔙 Volver a la lista",
        "header_set_btns": "⚙️ <b>Ajustes de visibilidad de botones:</b>",
        "header_set_profile": "👤 <b>Ajustes de visibilidad de tu perfil:</b>",
        "btn_accepts_on": "✅ Aceptar preguntas directas",
        "btn_accepts_off": "❌ No aceptar preguntas directas",
        "disp_anon_title": "Admin #X",
        "disp_name_title": "Nombre",
        "disp_username_title": "@username",
        "btn_unban_id": "🔓 Desbloquear (ID: {user_id})",
        "coadmin_text": "👥 <b>Enlace para añadir co-administrador:</b>\n<code>{inv_link}</code>\n\nReenvía este enlace al segundo administrador.",
        "ban_list_empty": "🎉 No hay usuarios bloqueados en este canal.",
        "ban_list_header": "🚫 <b>Usuarios bloqueados para este canal:</b>",
        "toast_unbanned": "✅ ¡Usuario desbloqueado con éxito!",

        "btn_manage_premium": "⭐ Ajustes Onward Premium",
        "premium_settings_header": "⭐ <b>Ajustes de Onward Premium:</b>",
        "btn_set_welcome": "🎨 Bienvenida personalizada",
        "btn_set_autoreply": "🤖 Auto-respuesta personalizada",
        "btn_copyright_on": "✅ Firma del bot activa",
        "btn_copyright_off": "❌ Firma del bot oculta",
        "prompt_enter_welcome": "🎨 Introduce el nuevo mensaje de bienvenida para los suscriptores:",
        "welcome_saved_success": "✅ ¡Mensaje de bienvenida guardado!",
        "welcome_reset_success": "🔄 Mensaje restablecido al predeterminado.",
        "prompt_enter_autoreply": "🤖 Introduce un mensaje de auto-respuesta para los suscriptores:",
        "autoreply_saved_success": "✅ ¡Auto-respuesta guardada con éxito!",
        "autoreply_reset_success": "🔄 Auto-respuesta desactivada.",
        "btn_ch_lang": "🌐 Idioma del canal: {curr_lang}",
        "header_ch_lang": "🌐 <b>Selecciona el idioma para las publicaciones del canal:</b>",
        "prompt_choose_user_lang": "🌐 <b>Selecciona tu idioma de interfaz para el bot:</b>",
        "toast_user_lang_updated": "✅ ¡Idioma de interfaz actualizado con éxito!",
        "toast_ch_lang_updated": "✅ ¡Idioma del canal actualizado con éxito!",
        "btn_reset": "🔄 Restablecer",
        "btn_channel_stats": "📊 Estadísticas y Exportación",
        "stats_menu_text": "📊 <b>Estadísticas de «{ch_title}»:</b>\n\n💡 <b>Ideas sugeridas:</b> {ideas_count}\n❓ <b>Preguntas recibidas:</b> {questions_count}\n⭐ <b>Total de reseñas:</b> {reviews_count}\n📈 <b>Calificación promedio:</b> {rating_avg} / 5.0\n✅ <b>Mensajes procesados:</b> {processed_count}",
        "btn_export_csv": "📥 Descargar reseñas en CSV",
        "err_no_reviews_export": "ℹ️ No hay reseñas disponibles para exportar.",
        "csv_file_caption": "📊 Exportación de reseñas para «{ch_title}»",

        "premium_menu_text": "⭐ <b>Onward Premium</b>\n\nDesbloquea funciones avanzadas para tu canal:\n• 🎨 Bienvenida y reglas personalizadas\n• 🤖 Auto-respuestas automáticas\n• 🚫 Ocultar firma del bot\n• 📊 Estadísticas detalladas y exportación\n\nElige un plan usando Telegram Stars:",
        "btn_plan_1d": "⭐ 1 Día — 5 XTR",
        "btn_plan_7d": "⭐ 7 Días — 20 XTR",
        "btn_plan_1m": "⭐ 1 Mes — 50 XTR",
        "btn_plan_3m": "⭐ 3 Meses — 120 XTR",
        "btn_plan_life": "⭐ Para siempre — 350 XTR",
        "plan_1d_title": "Onward Premium (1 Día)",
        "plan_7d_title": "Onward Premium (7 Días)",
        "plan_1m_title": "Onward Premium (1 Mes)",
        "plan_3m_title": "Onward Premium (3 Meses)",
        "plan_life_title": "Onward Premium (Para siempre)",
        "invoice_desc": "Acceso Premium para el canal {channel_id}",
        "pay_success": "🎉 <b>¡Pago exitoso!</b>\n\nEl estado <b>Onward Premium</b> está activo para el canal <code>{channel_id}</code>.\n¡Gracias por apoyar el proyecto!"
    }
}


def t(key: str, lang: str = "ru", **kwargs) -> str:
    lang_dict = TEXTS.get(lang, TEXTS["en"])
    text_template = lang_dict.get(key) or TEXTS["en"].get(key, key)
    if kwargs:
        try:
            return text_template.format(**kwargs)
        except KeyError:
            return text_template
    return text_template